// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gkd

import (
	"context"
	"time"
)

const insertRaw = `-- name: InsertRaw :one
INSERT INTO gkd_raw (
    station_id, station_slug, station_basin, station_name,
    water_temp_c, measured_at, raw_row_html
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (station_id, measured_at) DO NOTHING
RETURNING id
`

type InsertRawParams struct {
	StationID    string    `db:"station_id" json:"station_id"`
	StationSlug  string    `db:"station_slug" json:"station_slug"`
	StationBasin string    `db:"station_basin" json:"station_basin"`
	StationName  string    `db:"station_name" json:"station_name"`
	WaterTempC   *float64  `db:"water_temp_c" json:"water_temp_c"`
	MeasuredAt   time.Time `db:"measured_at" json:"measured_at"`
	RawRowHtml   *string   `db:"raw_row_html" json:"raw_row_html"`
}

func (q *Queries) InsertRaw(ctx context.Context, arg InsertRawParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRaw,
		arg.StationID,
		arg.StationSlug,
		arg.StationBasin,
		arg.StationName,
		arg.WaterTempC,
		arg.MeasuredAt,
		arg.RawRowHtml,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestPerStation = `-- name: LatestPerStation :many
SELECT DISTINCT ON (station_id)
    station_id, water_temp_c, measured_at
FROM gkd_raw
WHERE water_temp_c IS NOT NULL
ORDER BY station_id, measured_at DESC
`

type LatestPerStationRow struct {
	StationID  string    `db:"station_id" json:"station_id"`
	WaterTempC *float64  `db:"water_temp_c" json:"water_temp_c"`
	MeasuredAt time.Time `db:"measured_at" json:"measured_at"`
}

func (q *Queries) LatestPerStation(ctx context.Context) ([]LatestPerStationRow, error) {
	rows, err := q.db.Query(ctx, latestPerStation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPerStationRow
	for rows.Next() {
		var i LatestPerStationRow
		if err := rows.Scan(&i.StationID, &i.WaterTempC, &i.MeasuredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
