// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gkd

import (
	"context"
	"time"
)

const insertRaw = `-- name: InsertRaw :one
INSERT INTO gkd_raw (
    station_id, station_slug, station_basin, station_name,
    water_temp_c, measured_at, raw_row_html
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (station_id, measured_at) DO NOTHING
RETURNING id
`

type InsertRawParams struct {
	StationID    string    `db:"station_id" json:"station_id"`
	StationSlug  string    `db:"station_slug" json:"station_slug"`
	StationBasin string    `db:"station_basin" json:"station_basin"`
	StationName  string    `db:"station_name" json:"station_name"`
	WaterTempC   *float64  `db:"water_temp_c" json:"water_temp_c"`
	MeasuredAt   time.Time `db:"measured_at" json:"measured_at"`
	RawRowHtml   *string   `db:"raw_row_html" json:"raw_row_html"`
}

func (q *Queries) InsertRaw(ctx context.Context, arg InsertRawParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRaw,
		arg.StationID,
		arg.StationSlug,
		arg.StationBasin,
		arg.StationName,
		arg.WaterTempC,
		arg.MeasuredAt,
		arg.RawRowHtml,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const maxFetchedAt = `-- name: MaxFetchedAt :one
SELECT COALESCE(MAX(fetched_at), '1970-01-01 00:00:00+00'::TIMESTAMPTZ)::TIMESTAMPTZ AS max_fetched_at FROM gkd_raw
`

func (q *Queries) MaxFetchedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, maxFetchedAt)
	var max_fetched_at time.Time
	err := row.Scan(&max_fetched_at)
	return max_fetched_at, err
}
