// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gkd

import (
	"time"
)

type GkdRaw struct {
	ID           int64     `db:"id" json:"id"`
	StationID    string    `db:"station_id" json:"station_id"`
	StationSlug  string    `db:"station_slug" json:"station_slug"`
	StationBasin string    `db:"station_basin" json:"station_basin"`
	StationName  string    `db:"station_name" json:"station_name"`
	WaterTempC   *float64  `db:"water_temp_c" json:"water_temp_c"`
	MeasuredAt   time.Time `db:"measured_at" json:"measured_at"`
	RawRowHtml   *string   `db:"raw_row_html" json:"raw_row_html"`
	FetchedAt    time.Time `db:"fetched_at" json:"fetched_at"`
}
