// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package wachplan

import (
	"context"
	"encoding/json"
	"time"
)

const insertRaw = `-- name: InsertRaw :one
INSERT INTO wachplan_raw (
    sensor_id, upstream_id, app_id, dev_id,
    gtw_id, gtw_rssi, gtw_snr,
    air_temp_c, water_temp_c, humidity_pct, battery_v,
    measured_at, raw_payload
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13
)
ON CONFLICT (sensor_id, upstream_id) DO NOTHING
RETURNING id
`

type InsertRawParams struct {
	SensorID    string          `db:"sensor_id" json:"sensor_id"`
	UpstreamID  string          `db:"upstream_id" json:"upstream_id"`
	AppID       string          `db:"app_id" json:"app_id"`
	DevID       string          `db:"dev_id" json:"dev_id"`
	GtwID       *string         `db:"gtw_id" json:"gtw_id"`
	GtwRssi     *int32          `db:"gtw_rssi" json:"gtw_rssi"`
	GtwSnr      *float64        `db:"gtw_snr" json:"gtw_snr"`
	AirTempC    *float64        `db:"air_temp_c" json:"air_temp_c"`
	WaterTempC  *float64        `db:"water_temp_c" json:"water_temp_c"`
	HumidityPct *float64        `db:"humidity_pct" json:"humidity_pct"`
	BatteryV    *float64        `db:"battery_v" json:"battery_v"`
	MeasuredAt  time.Time       `db:"measured_at" json:"measured_at"`
	RawPayload  json.RawMessage `db:"raw_payload" json:"raw_payload"`
}

func (q *Queries) InsertRaw(ctx context.Context, arg InsertRawParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRaw,
		arg.SensorID,
		arg.UpstreamID,
		arg.AppID,
		arg.DevID,
		arg.GtwID,
		arg.GtwRssi,
		arg.GtwSnr,
		arg.AirTempC,
		arg.WaterTempC,
		arg.HumidityPct,
		arg.BatteryV,
		arg.MeasuredAt,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const maxFetchedAt = `-- name: MaxFetchedAt :one
SELECT COALESCE(MAX(fetched_at), '1970-01-01 00:00:00+00'::TIMESTAMPTZ)::TIMESTAMPTZ AS max_fetched_at FROM wachplan_raw
`

func (q *Queries) MaxFetchedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, maxFetchedAt)
	var max_fetched_at time.Time
	err := row.Scan(&max_fetched_at)
	return max_fetched_at, err
}
