// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package wachplan

import (
	"encoding/json"
	"time"
)

type WachplanRaw struct {
	ID          int64           `db:"id" json:"id"`
	SensorID    string          `db:"sensor_id" json:"sensor_id"`
	UpstreamID  string          `db:"upstream_id" json:"upstream_id"`
	AppID       string          `db:"app_id" json:"app_id"`
	DevID       string          `db:"dev_id" json:"dev_id"`
	GtwID       *string         `db:"gtw_id" json:"gtw_id"`
	GtwRssi     *int32          `db:"gtw_rssi" json:"gtw_rssi"`
	GtwSnr      *float64        `db:"gtw_snr" json:"gtw_snr"`
	AirTempC    *float64        `db:"air_temp_c" json:"air_temp_c"`
	WaterTempC  *float64        `db:"water_temp_c" json:"water_temp_c"`
	HumidityPct *float64        `db:"humidity_pct" json:"humidity_pct"`
	BatteryV    *float64        `db:"battery_v" json:"battery_v"`
	MeasuredAt  time.Time       `db:"measured_at" json:"measured_at"`
	RawPayload  json.RawMessage `db:"raw_payload" json:"raw_payload"`
	FetchedAt   time.Time       `db:"fetched_at" json:"fetched_at"`
}
