// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package generic

import (
	"context"
	"encoding/json"
	"time"
)

const insertRaw = `-- name: InsertRaw :one
INSERT INTO generic_raw (
    lake_slug, measured_at,
    temperature_2m_c, relative_humidity_2m_pct, wind_speed_10m_kmh, weather_code, is_day,
    raw_payload
) VALUES (
    $1, $2,
    $3, $4, $5, $6, $7,
    $8
)
ON CONFLICT (lake_slug, measured_at) DO NOTHING
RETURNING id
`

type InsertRawParams struct {
	LakeSlug              string          `db:"lake_slug" json:"lake_slug"`
	MeasuredAt            time.Time       `db:"measured_at" json:"measured_at"`
	Temperature2mC        *float64        `db:"temperature_2m_c" json:"temperature_2m_c"`
	RelativeHumidity2mPct *float64        `db:"relative_humidity_2m_pct" json:"relative_humidity_2m_pct"`
	WindSpeed10mKmh       *float64        `db:"wind_speed_10m_kmh" json:"wind_speed_10m_kmh"`
	WeatherCode           *int32          `db:"weather_code" json:"weather_code"`
	IsDay                 *bool           `db:"is_day" json:"is_day"`
	RawPayload            json.RawMessage `db:"raw_payload" json:"raw_payload"`
}

func (q *Queries) InsertRaw(ctx context.Context, arg InsertRawParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRaw,
		arg.LakeSlug,
		arg.MeasuredAt,
		arg.Temperature2mC,
		arg.RelativeHumidity2mPct,
		arg.WindSpeed10mKmh,
		arg.WeatherCode,
		arg.IsDay,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const maxFetchedAt = `-- name: MaxFetchedAt :one
SELECT COALESCE(MAX(fetched_at), '1970-01-01 00:00:00+00'::TIMESTAMPTZ)::TIMESTAMPTZ AS max_fetched_at FROM generic_raw
`

func (q *Queries) MaxFetchedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, maxFetchedAt)
	var max_fetched_at time.Time
	err := row.Scan(&max_fetched_at)
	return max_fetched_at, err
}
