name = "seebuddy-cron"
main = "src/index.js"
compatibility_date = "2026-01-01"

[triggers]
crons = ["*/15 * * * *"]

[vars]
POLL_URL = "https://staging-seebuddy-y3mi.encr.app/lakes/poll"
INGEST_URL = "https://staging-seebuddy-y3mi.encr.app/gkd/ingest"
